version: '3.7'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./website:/var/www/myapp
            - ./site.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - php
    php:
        image: php:7.4-fpm
        volumes:
            - ./website:/var/www/myapp
